config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: 'welcome#index'
  end
  devise_for :users, :controllers => { 
    :sessions => "user/sessions", 
    :registrations => "user/registrations",
    :omniauth_callbacks => "user/omniauth_callbacks"
  }
  get '/users/password', to: 'users#show_error'
  # ------------ navigator link  ---------------
  get '/searchsupercategoryid/:category_id', to: 'welcome#search_by_super_category_id', as: "search_by_super_category_id"
  get '/searchcategoryid/:category_id', to: 'welcome#search_by_category_id', as: "search_by_category_id"
  # ------------ elastic search ---------------
  get 'search', to: 'welcome#search'

  #----------Error page----------
  # match '/404', to: 'error/errors#not_found', via: :all, as: 'not_found'
  # match '/500', to: 'error/errors#internal_error', via: :all, as: 'internal_error'

  #----------Load data ajax-------------
  post '/getcate', to: 'posts#get_category_new', as: 'get_cate'
  post '/getcate_edit', to: 'posts#get_category_edit', as: 'get_cate_edit'
  post '/getdata', to: 'posts#get_data', as: 'get_data'

  #----------Change password-----------
  get '/confirm_password', to: 'users#confirm_old_password'
  post '/change_password', to: 'users#change_password'
  get '/change_password', to: 'users#edit_change_password'
  get '/edit_change_password', to: 'users#edit_change_password'
  
  #----------Login/ sign up/ logout------------
  get '/check_user', to: 'users#check_existed_user' #kiểm tra user tồn tại
  get '/check_email', to: 'users#check_email' #kiểm tra user tồn tại
  get '/check_login', to: 'users#check_login' #kiểm tra user và pass đúng hay chưa
  
  #----------Change locale------------
  # get '/locale', to: 'welcome#set_locale', as: 'set_locale'

  #----------Role User >> Post----------
  resources :users, only: [:edit, :update] do
    resources :posts, only: [:new, :edit, :update, :destroy, :create]  do
      resources :images,only: [:create, :edit, :update, :show, :destroy]
    end
  end
  resources :posts, only: [:show, :index]
  get '/index/user/:user_id/posts', to: 'posts#index_user_posts', as: 'index_user_posts' #liệt kê toàn bộ các bài viết của user 


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable, :timeoutable, :omniauthable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :posts

  # validates :name, presence: { message: "Tên không được để trống." }                         

  # validates :username, presence: { message: "Tên tài khoản không được để trống." },
  #                      length: {minimum: 6, maximum: 20, 
  #                      message: "Tên tài khoản phải có độ dài tối thiểu 6 ký tự và tối đa 20 ký tự."},
  #                      format: { with: /\A[a-zA-Z0-9]+\z?/, message: "Tên tài khoản không cho phép chứa ký tự đặc biệt."}

  # validates :email, presence: { message: "Địa chỉ email không được để trống." },
  #                   format: { with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|vn|info))\z/i,
  #                             message: "Địa chỉ email không hợp lệ." }


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      # if !auth.info.email.blank?
      #   user.email = auth.info.email
      # else
      #   user.email = "auth.uid"
      # end
      user.email = auth.info.email
      user.username = user.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!

    end

  end
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank? 
      end
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to root_path
    end 
  end
  def failure
    redirect_to root_path
  end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  layout false, except: [:edit]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
 
  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
    new_user_session_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  layout false
  before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_user!


  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
   super   
  end

  # DELETE /resource/sign_out
  def destroy
    super
    
  end
  protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password, :remember_me])
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :check_current_id, only: [:edit, :update]

  # GET /users/1
  # GET /users/1.json
  def edit
    @user = User.find(params[:id])
  end

  def show_error  
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      if @user.update(user_params)
        redirect_to edit_user_path (@user)
      end
  end

  #kiểm tra user có tồn tại hay ko
  def check_existed_user
    current_user_id = params[:current_user_id]
    @user = User.find_by_username (current_user_id)
    respond_to do |format|
      format.json { render :json => { check: !@user.nil? }} #check true thì có tồn tại user
    end
  end
  #kiểm tra tk vs mk
  def check_login
    user = User.find_by_username(params[:txtUsername].downcase)
      respond_to do |format|
        if user && BCrypt::Password.new(user.encrypted_password) == params[:txtPassword]
          format.json { render :json => { checkAll: true }}
        else
          format.json { render :json => { checkAll: false }} #false nghĩa là user or password ko đúng
        end
      end
  end
  #check mail có tồn tại hay ko
  def check_email
    email = params[:txt_email].downcase
    user = User.find_by_email (email)
    respond_to do |format|
      format.json { render :json => { checkEmail: !user.nil? }} #check true thì có tồn tại email
    end
  end
  def edit_change_password
    @user = User.new
  end
  # kiểm tra mật khẩu cũ
  def confirm_old_password
    @user = User.find_by_id(current_user.id)
    old_password = params[:old_password]
    respond_to do |format|
      if BCrypt::Password.new(@user.encrypted_password) == old_password
        format.json { render :json => { checkPwd: true }}
      else
        format.json { render :json => { checkPwd: false }}
      end
    end
  end

  def change_password
    @user = User.find_by_id(current_user.id)
    if @user.update_attributes(:password => params[:user][:change_password])
      flash[:noti_pwd] = 'Thay đổi mật khẩu thành công. Vui lòng đăng nhập lại.'    
      redirect_to new_user_session_path
    else
      flash[:noti_pwd] = 'Thay đổi mật khẩu thất bại'
    end
    # render 'edit_change_password'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    #or not_found or internal_server_error
    def set_user
      @user = User.find(params[:id]) or not_found or internal_server_error
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def data_params
      # bỏ require(:user) đi vì dữ liệu truyền về từ data
      params.permit(:name, :username, :password, :password_confirmation, :birthday, :gender, :email, :phone, :address, :personal)
    end
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation, :birthday, :gender, :email, :phone, :address, :personal)
    end
    #----Check url
    def check_current_id 
      @user = User.find(params[:id])
      redirect_to not_found_path if current_user.id != @user.id 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container-fluid" style='background-color: #E0F7FA'>
  <div class="row" style="padding-top: 50px;">  
    <!-- show personal -->
    <div class="col-sm-4 col-md-4">
      <div class="tung-edit-title col-md-12 font-weight-bold">
        <%# <span style="vertical-align: middle">Trang cá nhân</span> %>
      </div>
      <div class="card col-md-12">
        <%= image_tag("login-icon.png", class: 'avatar-img')%>
        <h1 style="margin-bottom: 30px"><%= @user.name %></h1>
        <%= link_to (t "change_password.change_password_title"), edit_change_password_path, class: 'btn btn-danger' %>
      </div>
    </div>
    <!-- show info -->
    <div class="col-sm-8 col-md-8">
      <div class="tung-edit-title col-md-12 font-weight-bold" style='text-align: left; margin-bottom: 20px'>
          <%# <span style="vertical-align: middle;">Thông tin cá nhân</span> %>
      </div>
      
      <div class="col-md-12">
        <%= form_with(model: @user, id: 'update_form', local: true) do |form| %>
          <!-- input Name -->
          <div class="form-group row edit-form-group">
            <label class="col-md-2 col-form-label font-weight-bold"><%= t "registry.fullname_label" %> <span class="obli">(*)</span></label>
            <div class="col-md-7">                     
              <%= form.text_field :name, id: :user_edit_name, onchange: 'checkEditName()', class: "form-control input-md"%>  
            </div>
            <p id="errorName" class='error'></p>
            <div class="col-md-3"></div>
          </div>       
          <!-- input Birthday -->
          <div class="form-group row edit-form-group">
            <label class="col-md-2 col-form-label font-weight-bold"><%= t "registry.birthday_label" %></label>
            <div class="col-md-7">
                <%= form.date_field :birthday, class: "form-control" %>
            </div>
            <div class="col-md-3"></div>
          </div>
          <!-- input Email -->
          <div class="form-group row edit-form-group">
            <label class="col-md-2 col-form-label font-weight-bold"><%= t "registry.email_label" %></label>
            <div class="col-md-7">
              <%= form.text_field :email, class: "form-control", disabled: true %>
            </div>
            <div class="col-md-3"></div>
          </div>
          <!-- input Gender -->
          <div class="form-group row edit-form-group">
            <label class="col-md-2 col-form-label font-weight-bold"><%= t "registry.sex_label" %></label>
            <div class="col-md-7">
              <label class="container-radio"><%= t "registry.sex_male" %>
                <%= form.radio_button :gender, 'male', checked: true %>
                <span class="checkmark"></span>
              </label>
              <label class="container-radio"><%= t "registry.sex_female" %>
                <%= form.radio_button :gender, 'female' %>
                <span class="checkmark"></span>
              </label>
            </div>
            <div class="col-md-3"></div>
          </div>
          <!-- input Phone -->
          <div class="form-group row edit-form-group">
            <label class="col-md-2 col-form-label font-weight-bold"><%= t "registry.phonenum_label" %></label>
            <div class="col-md-7">
              <%= form.text_field :phone, class: "form-control", id: :user_edit_phone, onchange: 'checkEditPhone()' %>
            </div>
            <p id="errorPhone" class='error'></p>
            <div class="col-md-3"></div>
          </div>
          <div class="form-group row edit-form-group">
            <label  class="col-md-2 col-form-label font-weight-bold"><%= t "registry.address_label" %></label>
            <div class="col-md-7">
              <%= form.text_field :address, class: "form-control" %>
            </div>
            <div class="col-md-3"></div>
          </div>
          <div class="row">
            <div class="col-md-4"></div>
            <%= form.submit (t "edit_user.save_label"), class: 'col-md-2 btn btn-primary', type: 'button', onclick: 'validateEditForm()' %>
            <span>&nbsp&nbsp</span>
            <%= link_to (t "edit_user.back_button"), root_path, class: 'col-md-2 btn btn-info' %>
            <div class="col-md-4"></div>
          </div>
          <% end %>
        </div>
      </div>
    </div>  
</div>
      
      

app/views/users/edit_change_password.html.erb
<%=  %><h1 style='text-align: center'><%= t "change_password.change_password_title" %></h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <%= form_for(@user, url: change_password_url) do |f| %>
            <div class="row">
                <span><%= t "change_password.old_password" %></span>
                <%= password_field_tag :old_password, nil, class: 'form-control' %>
            </div>
            <div class="row">
                <span id='oldPwd' class="error"></span>
            </div>
            <div id="div_2_button" style="margin-top: 20px" class="row">
                <div class="col-md-4"></div>
                <button type="button" id="btnConfirm" class="col-md-2 btn btn-dark" onclick="confirmOldPwd()"><%= t "change_password.confirm_button" %></button>
                <span>&nbsp&nbsp</span>
                <%= link_to (t "change_password.back_button"), edit_user_path(current_user.id), class: 'col-md-2 btn btn-info' %>
                <div class="col-md-4"></div>
            </div>
            <div id="formChangePwd" style="display: none;">
                <div class="row">
                    <span><%= t "change_password.new_password" %></span>
                    <%= f.password_field :change_password, class: 'form-control', onchange: 'checkPwd()' %>
                    <p id="errorPwd" class="error"></p>
                </div>
                <div class="row">
                    <span><%= t "change_password.confirm_new_password" %></span>      
                    <%= f.password_field :change_password_confirmation, class: 'form-control', onchange: 'checkPwdConfirm()' %>
                    <p id="errorPwdConfirm" class="error"></p>
                </div>
                <div class="row" style="margin-top: 20px">
                    <div class="col-md-3"></div>
                    <%= f.submit (t "change_password.change_button"), id: 'btnChangePwd', type: 'button', onclick: 'submitChangePwd()', class: "col-md-4 btn btn-primary" %>
                    <span>&nbsp&nbsp</span>
                    <%= link_to (t "change_password.back_button"), edit_user_path(current_user.id), class: 'col-md-2 btn btn-info' %>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <% end %>            
        </div>              
        <div class="col-md-3"></div>
        <div class="col-md-12"  style="text-align: center">
            <span id="noti_pwd" class="success"><%= flash[:noti_pwd] %></span>
        </div>
        
    </div>
</div>  

app/views/users/show_error.html.erb
<div class="container-fuild" style="padding: 100px 0px 100px 0px">
    <h2 style="text-align: center">
        Có gì đó không đúng, xin bạn hãy <a href="javascript:history.go(-1)">quay lại</a>!
    </h2>
</div>