config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: 'welcome#index'
  end
  devise_for :users, :controllers => { 
    :sessions => "user/sessions", 
    :registrations => "user/registrations",
    :omniauth_callbacks => "user/omniauth_callbacks"
  }
  get '/users/password', to: 'users#show_error'
  # ------------ navigator link  ---------------
  get '/searchsupercategoryid/:category_id', to: 'welcome#search_by_super_category_id', as: "search_by_super_category_id"
  get '/searchcategoryid/:category_id', to: 'welcome#search_by_category_id', as: "search_by_category_id"
  # ------------ elastic search ---------------
  get 'search', to: 'welcome#search'

  #----------Error page----------
  # match '/404', to: 'error/errors#not_found', via: :all, as: 'not_found'
  # match '/500', to: 'error/errors#internal_error', via: :all, as: 'internal_error'

  #----------Load data ajax-------------
  post '/getcate', to: 'posts#get_category_new', as: 'get_cate'
  post '/getcate_edit', to: 'posts#get_category_edit', as: 'get_cate_edit'
  post '/getdata', to: 'posts#get_data', as: 'get_data'

  #----------Change password-----------
  get '/confirm_password', to: 'users#confirm_old_password'
  post '/change_password', to: 'users#change_password'
  get '/change_password', to: 'users#edit_change_password'
  get '/edit_change_password', to: 'users#edit_change_password'
  
  #----------Login/ sign up/ logout------------
  get '/check_user', to: 'users#check_existed_user' #kiểm tra user tồn tại
  get '/check_email', to: 'users#check_email' #kiểm tra user tồn tại
  get '/check_login', to: 'users#check_login' #kiểm tra user và pass đúng hay chưa
  
  #----------Change locale------------
  # get '/locale', to: 'welcome#set_locale', as: 'set_locale'

  #----------Role User >> Post----------
  resources :users, only: [:edit, :update] do
    resources :posts, only: [:new, :edit, :update, :destroy, :create]  do
      resources :images,only: [:create, :edit, :update, :show, :destroy]
    end
  end
  resources :posts, only: [:show, :index]
  get '/index/user/:user_id/posts', to: 'posts#index_user_posts', as: 'index_user_posts' #liệt kê toàn bộ các bài viết của user 


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :load_data, only: [:index, :search_by_super_category_id, :search_by_category_id]
  def index
    @posts = newest_posts
    flash[:noti] = t(:noti_default)
    @search 
    # @categories = Category.where(super_id: nil)
    # @categories.each_with_index do |c, i|
    #   @categories[i].name = t(c.name)
    # end
    # puts @categories
    # @cities = City.all
    # @districts
    # find all city

    if(params[:city_id])
      @districts = City.find(params[:city_id]).districts.all
      respond_to do |format|  
        format.json { render json: @districts  }  
      end
    end
    # find district by city_id
    if( params[:category_id])
      @category_details = Category.where(super_id: params[:category_id])
      respond_to do |format|  
        format.json { render json: @category_details  }  
      end
    end
    # find ward by district_id
    if(params[:district_id])
      @wards = District.find(params[:district_id]).wards.all
      respond_to do |format|  
        format.json { render json: @wards  }  
      end
    end
    #find street by ward_id
    if( params[:ward_id])
      @street = Ward.find(params[:ward_id]).streets.all
      respond_to do |format|  
        format.json { render json: @street  }  
      end
    end
    #-------------------Search-----------
    if (params[:search_type])
     
      text = params[:search_normal]
      flash[:noti] = 'Kết quả tìm kiếm cho từ khóa "' + text + '"'
      if(params[:search_normal].nil?)
        @posts = []
      else
        @rs = Post.search params[:search_normal]     
        @posts = Post.where(id: @rs.pluck(:_id)).page(params[:page]).per(9)
      end
    end
    #------Advance search------
    if (params[:search])
      query = params.require(:search).permit(:category_id,:area_top, :area_bottom,:price_top, :price_bottom, :category_detail_id,:area,:price,:city_id, :district_id, :ward_id, :street_id, :house_direction, :bedroom)  
      @h = Array.new # search array only for area and price
      @s = "" # search string
      @h[0] = @s # h => [""]
      # LOOP query to edit search only for area and price
      query.each do |key, value|         
        # If query have a area top value
        if !value.blank? # value not blank
          case key
          when "area_bottom"
            if(@s != "") # string not blank , add ' AND '
             @s += ' AND '  # ex: @s => "area < ? AND "
            end
            # string blank , insert new query
            @s += "area >= ? " # ex: @s => "area < ? AND area > ?  "
            @h.push(value) # h => ["area < ?", "area_top_value"]
            query.delete(key) # delete key in query 
          when "area_top"
            if(@s != "") 
              @s += ' AND ' 
             end
            @s += "area <= ?" # ex @s => "area < ? AND area > ?  "
            @h.push(value)  # h => ["area < ? AND area > ?", "area_top_value", "area_bot_value"]
            query.delete(key) # delete key in query 
          when "price_top"
            if(@s != "") 
              @s += ' AND ' 
             end
            @s += "price <= ?" # ex @s => "area < ? AND area > ? AND price <= ?  "
            @h.push(value)  # h => ["area < ? AND area > ? AND price <= ?", "area_top_value", "area_bot_value", "price_top_value"]
            query.delete(key) # delete key in query 
          when "price_bottom"
            if(@s != "") 
              @s += ' AND ' 
              end
            @s += "price >= ?" # ex @s => "area < ? AND area > ? AND price <= ?  AND price >= ? "
            @h.push(value)  # h => ["area < ? AND area > ? AND price <= ?", "area_top_value", "area_bot_value", "price_top_value", "price_bot_value"]
            query.delete(key) # delete key in query
          when "bedroom"
            if !@s.blank?
              @s += ' AND ' 
            end
            @s += "bedroom >= ?" # @s => "bedroom >= ?"
            @h.push(value) # @h => ["bedroom >= ?", "bedroom_value"]
            query.delete(key) # delete key
          end
        end
        
        # IF
        if key == "category_detail_id" && !value.blank?
          query[:category_id] = query[:category_detail_id]
          query.delete(key)
        end
        if key == "category_detail_id" && value.blank?
          query[:category_id] = Category.where(super_id: query[:category_id])
        end
      end
      @h[0] = @s
      query.each do |key, value|
        if value.blank?
          query.delete(key)
        end
      end #end foreach

      if(!@s.blank?) # check array , prevent where null 
        @posts = Post.where(query).where(@h).order(created_at: :desc).page(params[:page]).per(9)
      elsif
        @posts = Post.where(query).order(created_at: :desc).page(params[:page]).per(9)
      end
        
      flash[:noti] = t(:noti_high_search)
    end #end if

  end

  def newest_posts
    @posts = Post.order(created_at: :desc).page(params[:page]).per(9)
    return @posts
  end

  def search_by_super_category_id
    query = Category.where(super_id: params[:category_id])

    @posts = Post.where(category_id: query).order(created_at: :desc).page(params[:page]).per(9)    
          
    flash[:noti] = t(:noti_high_search)
    render :index
  end

  def search_by_category_id

    @posts = Post.where(category_id: params[:category_id]).order(created_at: :desc).page(params[:page]).per(9)    
          
    flash[:noti] = t(:noti_high_search)
    render :index
  end
private
  def load_data
    @categories = Category.where(super_id: nil)#find all category parent
    @categories.each_with_index do |c, i|
      @categories[i].name = t(c.name)
    end
    @search_direction = Post::SEARCH_DIRECTION
    @search_direction_list = Hash.new
    @search_direction.each do |d|
      @search_direction_list[I18n.t(d)] = d
    end
    @cities = City.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_search.html.erb
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <style>
      #locationField, #controls {
        position: relative;
        width: 480px;
      }
      #autocomplete {
        position: absolute;
        top: 0px;
        left: 0px;
        width: 99%;
      }
      .label {
        text-align: right;
        font-weight: bold;
        width: 100px;
        color: #303030;
      }
      #address {
        border: 1px solid #000090;
        background-color: #f0f0ff;
        width: 480px;
        padding-right: 2px;
      }
      #address td {
        font-size: 10pt;
      }
      .field {
        width: 99%;
      }
      .slimField {
        width: 80px;
      }
      .wideField {
        width: 200px;
      }
      #locationField {
        height: 20px;
        margin-bottom: 2px;
      }
      #show-advance {
        color: white;
      }
      #full-search {
        padding: 30px;
        <%# padding-top: 30px;
        padding-bottom: 30px; %>
      }
      #advance-search {
        padding-left: 45px
      }
    </style>

<div class="container" style="padding-left:25px; padding-right:25px">
  <div style="background-color: white">
  <div id="full-search" class="container">
    <%= form_tag(root_path(locale:I18n.locale), method: "get", class: "row") do %>
    <%= hidden_field_tag(:search_type, "full") %>
    <%# <div class="col-md-1"></div> %>
    <div class="col-md-5">
      <%= text_field_tag(:search_normal, "", class: "form-control", placeholder: 'Nhập địa điểm') %>
    </div>
    <div class="col-md-4">
    <%= link_to t(:btn_search_high), '#all-search', 
    class: 'btn btn-primary col-md-12', data: {toggle: 'collapse'}  %> 
  </div>
    <div class="col-md-3">
      <%= submit_tag(t(:btn_search),name: nil, class: "btn btn-success col-md-12") %>
    </div>
    <% end %>     
  </div>

  <div id="all-search" class="collapse col-md-12" style="background-color: white">
  <%= form_for(:search, url:root_path(locale:I18n.locale), method: "get") do |f| %>
    <%= f.hidden_field :search_type, :value => "advance" %>
    <div class="row">
    
      <div id="advance-search" class="col-md-6">
        <!-- LOAD GGMAP LIBRARY -->
        
          <!-- CATEGORY select -->
            <div class="category">
                <%= f.select :category_id, options_from_collection_for_select(@categories, :id, :name),
                  {prompt: t(:select_category)}, {class: 'row form-control margin-form'} %>
            </div>
            <div id="category-detail">
                <%= f.select :category_detail_id, "<option></option>",
                {prompt: t(:select_type)}, {class: 'row form-control margin-form'} %>
            </div>
            <!-- CITY SELECT -->
            <div class="city">
                <%= f.select :city_id, options_from_collection_for_select(@cities, "id", "name", params[:id]),
                  {prompt: t(:select_city)}, {class: 'row form-control margin-form'} %>
            </div>
            <!-- DISTRICT SELECT -->
            <div class="district">
                <%= f.select :district_id, '<option></option>', 
                {include_blank: true, prompt: t(:select_district)}, {class: 'row form-control margin-form'}  %>
            </div>
            <!-- AREA  -->
            <div class="field row margin-form">
              <div class="col-sm-4 col-lg-4"><%= t(:search_area) %></div>
              <%= f.text_field :area_bottom, id: :area_bottom, class: 'form-control col-md-3' %>
              <div class="col-sm-2 col-lg-2"><%= t(:to) %></div>
              <%= f.text_field :area_top, id: :area_top, class: 'form-control col-md-3' %>
            </div>
            <div class="field row margin-form">
              <div class="col-sm-4 col-lg-4"><%= t(:search_price) %></div>   
              <%= f.text_field :price_bottom, id: :price_bottom, class: 'form-control col-md-3' %>
              <div class="col-sm-2 col-lg-2"><%= t(:to) %></div>   
                <%= f.text_field :price_top, id: :price_top, class: 'form-control col-md-3' %>
            </div>

            <%= link_to t(:more_detail), '#super_advance', data: {toggle: 'collapse'}, style: 'text-decoration: underline;' %>
      </div>    

    <!-- SUPER ADVANCE -->
      <div id="super_advance" class="collapse col-md-6" style="padding: 0px 30px 0px 30px">
          <!-- WARD -->
        <div class="ward margin-form">
          <%= f.select :ward_id,"<option></option>", {prompt: t(:select_ward)}, {class: 'form-control'} %>
        </div>
        <!-- STREET -->
        <div class="street margin-form">
          <%= f.select :street_id,"<option></option>", {prompt: t(:select_street)}, {class: 'form-control'} %>
        </div>
        <!-- HOUSE DIRECTION -->
        <div class="house_direction margin-form">
          <%= f.select :house_direction, @search_direction_list,
          {prompt: t(:house_direction)}, {class: 'form-control'} %>               
        </div>
        <!-- BEDROOM -->
        <div class="bedroom margin-form">
          <%= f.select :bedroom,("<option value=''>" + t(:unknow) + "</option><option value=1>1+</option><option value=2>2+</option><option value=3>3+</option><option value=4>4+</option><option value=5>5+</option>").html_safe,
          {prompt: t(:bedroom)}, {class: 'form-control'} %>                               
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4" style="padding: 0px 30px 0px 30px">
          <%= f.submit (t(:btn_search)), class: 'btn btn-info col-md-12', style: 'margin-top: 20px' %>
      </div>
      <div class="col-md-4"></div>
    </div>
  <% end %>
  </div>
</div>
</div>

<script>
        // This example displays an address form, using the autocomplete feature
        // of the Google Places API to help users fill in the information.
  
        // This example requires the Places library. Include the libraries=places
        // parameter when you first load the API. For example:
        // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
        var address = {};
        var placeSearch, autocomplete;
  
        function initAutocomplete() {
          // Create the autocomplete object, restricting the search to geographical
          // location types.
          autocomplete = new google.maps.places.Autocomplete(
              /** @type {!HTMLInputElement} */(document.getElementById('query')),
              {types: ['geocode']});
  
          // When the user selects an address from the dropdown, populate the address
          // fields in the form.
          autocomplete.addListener('place_changed', fillInAddress);
        }
  
        function fillInAddress() {
          // Get the place details from the autocomplete object.
          var place = autocomplete.getPlace();
          address = passData(place.address_components);
          
          
        }
  
        // Bias the autocomplete object to the user's geographical location,
        // as supplied by the browser's 'navigator.geolocation' object.
        function geolocate() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var geolocation = {
                lat: position.coords.latitude,
                lng: position.coords.longitude
              };
              var circle = new google.maps.Circle({
                center: geolocation,
                radius: position.coords.accuracy
              });
              autocomplete.setBounds(circle.getBounds());
            });
          }
        }
        // convert place to object
        function passData(model) {
            for(var i = 0; i < model.length; i++) {
                var addressType = model[i].types[0];
                if (addressType === 'administrative_area_level_1') {
                    address.city = model[i].long_name;
                  }
                  if(addressType == "administrative_area_level_2")
                  {
                    address.district = model[i].long_name;
                  }
                  if(addressType == "sublocality_level_1")
                  {
                    address.ward = model[i].long_name;
                  }
                  if(addressType == "route")
                  {
                    address.street = model[i].long_name;
                  }
                  if(addressType == "street_number")
                  {
                    address.add = model[i].long_name;
                  }
            } // end for
            console.log(address);
        
            
          }
      </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnFxsxcFARq6WccD-0Nm3J0qw4DpQ_F2w&libraries=places&callback=initAutocomplete"></script>
      

app/views/welcome/index.html.erb
<div style="background-color: gainsboro">
<div class="container">
    <div id="tung-div-search" class="row">
        <%= render 'search'%>
    </div>
    <div class="container">
    <div class="row">
        <h3 class="post-noti col-md-12"><%= flash[:noti] %></h3> 
    </div>
</div>
<% if !@posts.present? %>    
<div class="container">
    <div class="row">
        <h3 class="post-noti col-md-12"><%= t "welcome.no_result_notice" %></h3> 
    </div>
</div>
<% else %>
    <div class="container">
        <div id="tung-div-show" class="row">
            <% @posts.each do |post|%>
                <div class="post-member col-md-6 col-lg-4">
                    <div class="container pmb-detail">
                        <div class="row">
                            <div class="pmb-header">
                                <div class="pmb-date">
                                    <p class="day"><%= post.created_at.day %></p>
                                    <p class="month"><%= post.created_at.strftime(t("welcome.month"))  %>

                                    </p>
                                </div>
                                <div>
                                <%= link_to post.title, post_path(post.id), class: 'pmb-title'%>
                                </div>
                            </div>
                                <% if post.images.empty? %>
                                    <div class="pmb-img"
                                            style="background-image: url(<%= asset_url "default.jpg"%>)"
                                        >
                                    </div>
                                    <% else %>
                                    <% if post.images.first.url != nil && post.images.first.url.length > 0 %>
                                        <div class="pmb-img"
                                            style="background-image: url(<%= asset_url post.images.first.url%>)"
                                        >
                                        </div>
                                        <% else %>
                                        <div class="pmb-img"
                                            style="background-image: url(<%= post.images.first.url_out%>)"
                                        >
                                        </div>
                                    <% end %>
                                <% end %>
                                                            
                            <div class="pmb-content">
                                <div>  
                                    <p>
                                        <span><%= t "welcome.price" %> </span>
                                        <% if post.unit == 'agreement' %>                                        
                                        <span>
                                            <%= t 'agreement' %>
                                        <%else%>
                                            
                                            <% if  post.unit == 'million'%>
                                             <%= post.price %><%= t 'million' %>   
                                            <% elsif post.unit == 'billion' %>
                                              <%= post.price %><%= t 'billion' %>
                                            <% elsif post.unit == 'hunderm2' %>
                                              <%= post.price %><%= t 'hunderm2' %>
                                            <% else %>
                                              <%= post.price %><%= t 'millionm2' %>
                                            <% end %>                                    
                                        </span>
                                        <% end %>
                                    <p>
                                        <span><%= t "welcome.erea" %></span>
                                        <span><%= post.area %> m²</span>
                                    </p>
                                    <p>
                                        <span><%= t "welcome.address" %></span>
                                        <span><%= post.address_number %></span>
                                    </p>
                                </div>                    
                            </div>
                        </div>
                    </div>
                </div>     
            <% end %>
        </div>
    </div>

    <%= paginate @posts, theme: 'twitter-bootstrap-4', outer_window: 3 %>
    
<% end %>
</div>

</div>