config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: 'welcome#index'
  end
  devise_for :users, :controllers => { 
    :sessions => "user/sessions", 
    :registrations => "user/registrations",
    :omniauth_callbacks => "user/omniauth_callbacks"
  }
  get '/users/password', to: 'users#show_error'
  # ------------ navigator link  ---------------
  get '/searchsupercategoryid/:category_id', to: 'welcome#search_by_super_category_id', as: "search_by_super_category_id"
  get '/searchcategoryid/:category_id', to: 'welcome#search_by_category_id', as: "search_by_category_id"
  # ------------ elastic search ---------------
  get 'search', to: 'welcome#search'

  #----------Error page----------
  # match '/404', to: 'error/errors#not_found', via: :all, as: 'not_found'
  # match '/500', to: 'error/errors#internal_error', via: :all, as: 'internal_error'

  #----------Load data ajax-------------
  post '/getcate', to: 'posts#get_category_new', as: 'get_cate'
  post '/getcate_edit', to: 'posts#get_category_edit', as: 'get_cate_edit'
  post '/getdata', to: 'posts#get_data', as: 'get_data'

  #----------Change password-----------
  get '/confirm_password', to: 'users#confirm_old_password'
  post '/change_password', to: 'users#change_password'
  get '/change_password', to: 'users#edit_change_password'
  get '/edit_change_password', to: 'users#edit_change_password'
  
  #----------Login/ sign up/ logout------------
  get '/check_user', to: 'users#check_existed_user' #kiểm tra user tồn tại
  get '/check_email', to: 'users#check_email' #kiểm tra user tồn tại
  get '/check_login', to: 'users#check_login' #kiểm tra user và pass đúng hay chưa
  
  #----------Change locale------------
  # get '/locale', to: 'welcome#set_locale', as: 'set_locale'

  #----------Role User >> Post----------
  resources :users, only: [:edit, :update] do
    resources :posts, only: [:new, :edit, :update, :destroy, :create]  do
      resources :images,only: [:create, :edit, :update, :show, :destroy]
    end
  end
  resources :posts, only: [:show, :index]
  get '/index/user/:user_id/posts', to: 'posts#index_user_posts', as: 'index_user_posts' #liệt kê toàn bộ các bài viết của user 


end

app/models/post.rb
require 'elasticsearch/model'
require 'elasticsearch/model'

class Post < ApplicationRecord
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    belongs_to :user
    has_many :images, dependent: :destroy
    accepts_nested_attributes_for :images

    DIRECTION = [
        'east','west','south', 'north'
    ]
    SEARCH_DIRECTION = [
        'east','west','south', 'north', 'unknow'
    ]
    UNIT_POST =['agreement', 'million', 'billion', 
        'hunderm2', 'millionm2']
  
    CATEGORY_LIST_POST =  {
        "house_land_sell" => I18n.t(:house_land_sell),
        "house_land_rent" => I18n.t(:house_land_rent),
        "apartments_sell" => I18n.t(:apartments_sell), 
        "house_sell" => I18n.t(:house_sell), 
        "land_sell" => I18n.t(:land_sell), 
        "villas_sell" => I18n.t(:villas_sell), 
        "house_rent" => I18n.t(:house_rent), 
        "apartments_rent" => I18n.t(:apartments_rent), 
        "office_rent" => I18n.t(:office_rent), 
        "hostel_rent" => I18n.t(:hostel_rent)
    }
    # Check foreign key exists
    validate :category_id_exists
    validate :city_id_exists
    validate :district_id_exists
    
    # Can not be blank
    validates :title, :description, :category_id, :city_id,
        :district_id, :address_number, :contact_mobile, presence: true
    #Length
    validates :title, length: {minimum:30, maximum:99}
    validates :description, length: {minimum:30, maximum:3000}
    validates :address_number,length: {maximum:200}
    validates :furniture, length: {maximum:200, allow_blank: true}  
    validates :contact_address, length: {maximum:200, allow_blank: true}    
        #Format
    validates :contact_mobile, length: {minimum:10, maximum:11}, format: {with: /\d{10,11}/}
    validates :contact_phone, length: {minimum:10, maximum:11},  format: {with: /\d{10,11}\z/}, allow_blank:true
    validates :contact_mail, allow_blank:true, length: {maximum: 100}, 
        format: { with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i}
    validates :contact_name, allow_blank:true, length: {maximum:200}, format: {with: /\A[a-zA-Z]+\z?/}
    validates :project, allow_blank:true, length: {maximum:200}, format: {with: /\A[a-zA-Z]+\z?/}
        #Num
    validates :price, allow_blank:true, numericality: {only_float: true, greater_than: 0, less_than_or_equal_to: 999999}
    validates :area, allow_blank:true, numericality: {only_float: true, greater_than: 0, less_than_or_equal_to: 999999 }
    validates :front, allow_blank:true, numericality: {only_float: true, greater_than: 0, less_than_or_equal_to: 999999}
    validates :entrance, allow_blank:true, numericality: {only_float: true, greater_than: 0, less_than_or_equal_to: 999999}
    validates :floor, allow_blank:true, numericality: {only_integer: true, greater_than:0, less_than_or_equal_to: 999}
    validates :bedroom, allow_blank:true, numericality: {only_integer: true, greater_than:0, less_than_or_equal_to: 999}
    validates :toilet,allow_blank:true, numericality: {only_integer: true, greater_than:0, less_than_or_equal_to: 999}
    
    protected
    def category_id_exists
        begin
          Category.find(self.category_id)
        rescue ActiveRecord::RecordNotFound
          errors.add(:category_id, :exit_category)
          false
        end
    end
    def city_id_exists
        begin
          City.find(self.city_id)
        rescue ActiveRecord::RecordNotFound
          errors.add(:city_id,:exit_city)
          false
        end
    end
    def district_id_exists
        begin
          District.find(self.district_id)
        rescue ActiveRecord::RecordNotFound
          errors.add(:district_id, :exit_district)
          false
        end
    end
        
    
end

# Post.import force: true

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_post_to_show, only: [:show]
  before_action :check_current_id, only: [:edit, :update, :destroy] 
  before_action :load_data, only: [:edit, :new]
  #GET /user_posts
  #GET /user_posts.json
  def index_user_posts
    @user = current_user
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(5)  #phân trang 
  end

  # GET /posts/new
  def new
    @post = Post.new
    @image = @post.images.build
    load_data()
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.where(super_id: nil) #find all category parent
    load_data()
  end

  # POST users/id/posts
  # POST users/id/posts.json
  def create
    @user = current_user    
    @post = @user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        if !(params[:images].nil?)
          params[:images]['url'].each do |a|
            @image = @post.images.create!(url: a, post_id: @post.id)
          end
        end
        format.html { redirect_to post_path(@post), notice: 'Bài viết đã được đăng thành công.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    # @user = current_user
    # @p = Post.find(params(:id))
    # if @p.user_id == @user.id
      # @post = @user.posts.find(params[:id])
      respond_to do |format|
        if @post.update(post_params)
          if !(params[:images].nil?)
            params[:images]['url'].each do |a|
              @image = @post.images.create!(url: a, post_id: @post.id)
            end
          end
          if !(params[:images_delete].nil?)
            params[:images_delete].each do |i|
              image = Image.find(i['id']);
              @post.images.destroy(image);
            end
          end
          format.html { redirect_to @post, notice: 'Bài viết đã được chỉnh sửa thành công.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    # else
    #   redirect_to not_found_path
    # end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # @user = current_user
    # @post = Post.find(params[:id])
    # if @user.id == @post.user_id
      @post.destroy
      respond_to do |format|
        format.html { redirect_to index_user_posts_path(@user), notice: 'Bài viết đã được xóa thành công.' }
        format.json { head :no_content }
      end
    # else
    #   redirect_to not_found_path
    # end
  end

 #NEW
 def get_category_new
    @sub_cate = Category.where('super_id = ? ', params[:category_id]) #find all child          
    respond_to do |format|
      format.json { render json: @sub_cate } 
    end
  end
  #EDIT
  def get_category_edit
      #get super id in post edit
      @tmp = Category.where('id = ?', params[:category_id]) #category in post edit
      @sCategory = Category.where('super_id = ?', @tmp[0].super_id)  #category child when load page
      @list_child_categories = Category.where('super_id = ? ', params[:category_id]) #categories child dropdown

      respond_to do |format|
        format.json { render json: [@sCategory, @list_child_categories, @tmp] }
      end
  end

  
  def get_data 
    if params[:city_id]
      @districts = City.find(params[:city_id]).districts.all
      respond_to do |format|  
        format.json { render json: [@cities, @districts] }  
      end
    end
    if params[:district_id]
      @wards = District.find(params[:district_id]).wards.all
      respond_to do |format|
        format.json { render json: @wards }
      end
    end
    if params[:ward_id]
      @streets = Ward.find(params[:ward_id]).streets.all
      respond_to do |format|
        format.json { render json: @streets }
      end
    end 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id]) or not_found or internal_server_error
    end
    def set_post_to_show
      @post = Post.includes(:images).find(params[:id])

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title,:description, :user_id,
      :category_id, :city_id, :district_id, :ward_id, 
      :street_id, :address_number,:project, :unit, 
      :area, :price,:front, :entrance,
      :lng, :lat, 
      :house_direction, :balcony_direction, 
      :floor, :bedroom, :toilet, :furniture, 
      :contact_name, :contact_address, :contact_phone, :contact_mobile, :contact_mail,
      images_attributes: [:id, :post_id, :url])
    end  

  def check_current_id
    @user = current_user
    @post = Post.find(params[:id])
    redirect_to not_found_path unless @user.id == @post.user_id
  end

  def load_data
    @categories = Category.where(super_id: nil)#find all category parent
    @categories.each_with_index do |c, i|
      @categories[i].name = t(c.name)
    end
    
    @units = Post::UNIT_POST
    @units_hash = Hash.new
    @units.each do |u|
      @units_hash[I18n.t(u)] =  u
    end
    
    @direction = Post::DIRECTION
    @direction_list = Hash.new
    @direction.each do |d|
      @direction_list[I18n.t(d)] = d
    end
    @cities = City.all
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_search.html.erb
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <style>
      #locationField, #controls {
        position: relative;
        width: 480px;
      }
      #autocomplete {
        position: absolute;
        top: 0px;
        left: 0px;
        width: 99%;
      }
      .label {
        text-align: right;
        font-weight: bold;
        width: 100px;
        color: #303030;
      }
      #address {
        border: 1px solid #000090;
        background-color: #f0f0ff;
        width: 480px;
        padding-right: 2px;
      }
      #address td {
        font-size: 10pt;
      }
      .field {
        width: 99%;
      }
      .slimField {
        width: 80px;
      }
      .wideField {
        width: 200px;
      }
      #locationField {
        height: 20px;
        margin-bottom: 2px;
      }
    </style>
<div id="full-search">
    <%= form_tag("/posts/result", method: "get") do %>
    <%= label_tag(:query, "Search for:") %>
    <%= hidden_field_tag(:search_type, "full") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Search") %>
    <% end %>    
<a type="button" id='show-advance' class="btn btn-primary" onclick="onChangeForm('advance-search', 'full-search',)">advance search</a>
        
</div>
<div id="advance-search" style="display: none">
    <!-- LOAD GGMAP LIBRARY -->
    
    <%= form_for(:search, url:"/posts/result", method: "get" ) do |f| %>
        <%= f.hidden_field :search_type, :value => "advance" %>
        <!-- CATEGORY select -->
        <div class="category">
            <%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "--Select category--"%>
        </div>
        <div id="category-detail" style="display:none;">
            <%= f.select :category_detail_id, "<option></option>", prompt: "--Select specific category--"%>
        </div>
        <!-- CITY SELECT -->
        <div class="city">
            <%= f.select :city_id, options_from_collection_for_select(@cities, "id", "name", params[:id]), prompt: "--Select city--" %>
        </div>
        <!-- DISTRICT SELECT -->
        <div class="district">
            <%= f.select :district_id,"<option></option>", include_blank: true, prompt: "--Select district" %>
        </div>
        <!-- AREA  -->
        <div class="field">
            <%= f.label :area_bottom %>
            <%= f.text_field :area_bottom, id: :area_bottom %>
        </div>
        <div class="field">
            <%= f.label :area_top %>
            <%= f.text_field :area_top, id: :area_top %>
        </div>
        <!-- PRICE  -->
        <div class="field">
            <%= f.label :price_bottom %>
            <%= f.text_field :price_bottom, id: :price_bottom %>
        </div>
        <div class="field">
            <%= f.label :price_top %>
            <%= f.text_field :price_top, id: :price_top %>
        </div>
        <button type="button" id="btnShowSAdvance" class="btn btn-success" >Show super advance</button>
        <!-- SUPER ADVANCE -->
        <div id="super_advance" style="display: none;">
            <!-- WARD -->
            <div class="ward">
                <%= f.select :ward_id,"<option></option>", prompt: "--Select ward" %>
            </div>
            <!-- STREET -->
            <div class="street">
                <%= f.select :street_id,"<option></option>", prompt: "--Select street" %>
            </div>
            <!-- HOUSE DIRECTION -->
            <div class="house_direction">
                    <%= f.select :house_direction,"<option value="">Không xác định</option><option value='Đông'>Đông</option><option value='Tây'>Tây</option><option value='Nam'>Nam</option><option value='Bắc'>Bắc</option><option value='Đông-Bắc'>Đông-Bắc</option><option value='Tây-Bắc'>Tây-Bắc</option><option value='Tây-Nam'>Tây-Nam</option><option value='Đông-Nam'>Đông-Nam</option>".html_safe, prompt: "--Select house direction" %>               
            </div>
            <!-- BEDROOM -->
            <div class="bedroom">
                <%= f.select :bedroom,"<option value="">Không xác định</option><option value=1>1+</option><option value=2>2+</option><option value=3>3+</option><option value=4>4+</option><option value=5>5+</option>".html_safe, prompt: "--Select house direction" %>                               
            </div>
        </div>
        <div class="actions">
            <%= f.submit %>
        </div>
    <% end %>
    
<a id='show-full' class="btn btn-primary" onclick="onChangeForm('full-search', 'advance-search')">full search</a>

</div>
<script>
        var address = {};
        var placeSearch, autocomplete;
  
        function initAutocomplete() {
          // Create the autocomplete object, restricting the search to geographical
          // location types.
          autocomplete = new google.maps.places.Autocomplete(
              /** @type {!HTMLInputElement} */(document.getElementById('query')),
              {types: ['geocode']});
  
          // When the user selects an address from the dropdown, populate the address
          // fields in the form.
          autocomplete.addListener('place_changed', fillInAddress);
        }
  
        function fillInAddress() {
          // Get the place details from the autocomplete object.
          var place = autocomplete.getPlace();
          address = passData(place.address_components);
        }
  
        // Bias the autocomplete object to the user's geographical location,
        // as supplied by the browser's 'navigator.geolocation' object.
        function geolocate() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var geolocation = {
                lat: position.coords.latitude,
                lng: position.coords.longitude
              };
              var circle = new google.maps.Circle({
                center: geolocation,
                radius: position.coords.accuracy
              });
              autocomplete.setBounds(circle.getBounds());
            });
          }
        }
        // convert place to object
        function passData(model) {
            for(var i = 0; i < model.length; i++) {
                var addressType = model[i].types[0];
                if (addressType === 'administrative_area_level_1') {
                    address.city = model[i].long_name;
                  }
                  if(addressType == "administrative_area_level_2")
                  {
                    address.district = model[i].long_name;
                  }
                  if(addressType == "sublocality_level_1")
                  {
                    address.ward = model[i].long_name;
                  }
                  if(addressType == "route")
                  {
                    address.street = model[i].long_name;
                  }
                  if(addressType == "street_number")
                  {
                    address.add = model[i].long_name;
                  }
            } // end for       
          }
      </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnFxsxcFARq6WccD-0Nm3J0qw4DpQ_F2w&libraries=places&callback=initAutocomplete"></script>
      

app/views/posts/edit.html.erb
<div class="container">
    <h2 style="text-align: center;"><%= t(:edit_post_title) %></h3>
    <%= render 'form-edit', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <%= render 'search'%>
  <h1>Posts</h1>
  <% @posts.each do |post|%>
        <%= post.title %>
        </br>
    <% end %>
    <%= paginate @posts %>
  <br>
  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/index_user_posts.html.erb
<h4 style="text-align: center;margin-top:20px;"><%= t(:index_posts_user_title, name: @user.name) %></h4>
<div class="container">
        <table class="table table-hover" style="text-align: center;">
            <thead>
                <tr>
                    <th>#</th>
                    <th><%= t(:title) %></th>
                    <th><%= t(:create_day) %></th>
                    <th><%= t(:show_post) %></th>
                    <th><%= t(:edit_post) %></th>
                    <th><%= t(:delete_post) %></th>
                </tr>
            </thead>
            <tbody>
                <% @posts.each.with_index(1) do |post, index| %>
                    <tr>
                        <th scope="row"><%= index %> </th>
                        <td style="text-align: left;"><%= post.title%></td>
                        <td><%= post.created_at.strftime(t(:time_zone_create)) %></td>
                        <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, post_path(post) %></td>
                        <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_user_post_path(@user.id ,post) %></td>
                        <td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, user_post_path(@user.id, post), method: :delete, data: { confirm: 'Bạn có chắc muốn xóa bài viết này không?' } %> </td>
                    </tr>
                <%end%>
            </tbody>
        </table>
        <%= paginate @posts, theme: 'twitter-bootstrap-4', outer_window: 3 %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h3 style="text-align: center;"><%= t(:new_post_title) %></h3>
  <span style="color:gray;"><%= t(:new_post_sub) %></span>
  <%= render 'form-create', post: @post %>
</div>

<!-- <%= link_to 'Back', posts_path %> -->

app/views/posts/result.html.erb
<% if !@posts.present? %>    
    <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% else %>
    <h1>Posts</h1>
    <% @posts.each do |post|%>
        <%= post.title %> <%= post.created_at %>
        </br>
    <% end %>
    <%= paginate @posts, theme: 'twitter-bootstrap-4', outer_window: 3 %>
<% end %>