config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: 'welcome#index'
  end
  devise_for :users, :controllers => { 
    :sessions => "user/sessions", 
    :registrations => "user/registrations",
    :omniauth_callbacks => "user/omniauth_callbacks"
  }
  get '/users/password', to: 'users#show_error'
  # ------------ navigator link  ---------------
  get '/searchsupercategoryid/:category_id', to: 'welcome#search_by_super_category_id', as: "search_by_super_category_id"
  get '/searchcategoryid/:category_id', to: 'welcome#search_by_category_id', as: "search_by_category_id"
  # ------------ elastic search ---------------
  get 'search', to: 'welcome#search'

  #----------Error page----------
  # match '/404', to: 'error/errors#not_found', via: :all, as: 'not_found'
  # match '/500', to: 'error/errors#internal_error', via: :all, as: 'internal_error'

  #----------Load data ajax-------------
  post '/getcate', to: 'posts#get_category_new', as: 'get_cate'
  post '/getcate_edit', to: 'posts#get_category_edit', as: 'get_cate_edit'
  post '/getdata', to: 'posts#get_data', as: 'get_data'

  #----------Change password-----------
  get '/confirm_password', to: 'users#confirm_old_password'
  post '/change_password', to: 'users#change_password'
  get '/change_password', to: 'users#edit_change_password'
  get '/edit_change_password', to: 'users#edit_change_password'
  
  #----------Login/ sign up/ logout------------
  get '/check_user', to: 'users#check_existed_user' #kiểm tra user tồn tại
  get '/check_email', to: 'users#check_email' #kiểm tra user tồn tại
  get '/check_login', to: 'users#check_login' #kiểm tra user và pass đúng hay chưa
  
  #----------Change locale------------
  # get '/locale', to: 'welcome#set_locale', as: 'set_locale'

  #----------Role User >> Post----------
  resources :users, only: [:edit, :update] do
    resources :posts, only: [:new, :edit, :update, :destroy, :create]  do
      resources :images,only: [:create, :edit, :update, :show, :destroy]
    end
  end
  resources :posts, only: [:show, :index]
  get '/index/user/:user_id/posts', to: 'posts#index_user_posts', as: 'index_user_posts' #liệt kê toàn bộ các bài viết của user 


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverLandV2</title>
    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">  
        I18n.defaultLocale = "<%= I18n.default_locale %>"
        I18n.locale = "<%= I18n.locale || I18n.default_locale %>"
    </script> 
  </head>
  <body onLoad="myFunction()">
    <div class="container-fluid nav-fixed">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <%= link_to  "Everland", root_path, class: 'navbar-brand'%>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if @menu_category.present?%>
                <ul class="navbar-nav mr-auto">
                    <% @menu_category.each do |item| %>
                        <div class="dropdown btn btn-light" style="float:left" >          
                    <%#= link_to t(item[:super_cate].name), "/?search[category_id]=" + item[:super_cate].id.to_s + "&search[category_detail_id]",
                                style:"color:black; text-decoration: none;" %>    

                               <%= link_to t(item[:super_cate].name), search_by_super_category_id_path(category_id: item[:super_cate].id),
                               style:"color:black; text-decoration: none;" %>       

                            <div class="dropdown-content" style="left:0; min-width: 200px" >
                                <% item[:sub_cate].each do |category| %>
                                <%= link_to t(category.name), search_by_category_id_path(category_id: category.id),
                                    class:"dropdown-item" %>       
                                <% end %>
                            </div>
                        </div>
                    <% end %> <!-- end for -->
                </ul>
            <% end %> <!-- end if -->
            <!-- Chuyen ngon ngu -->
            <div data-turbolinks="false">
            <%= link_to_unless I18n.locale == :en, "EN", locale: :en %>
            <span>&nbsp</span> |  <span>&nbsp</span>
            <%= link_to_unless I18n.locale == :vi, "VI", locale: :vi %>
            <span>&nbsp&nbsp</span>
            </div>
                <!-- Nút Post -->
            <% if user_signed_in? %>
                <%= link_to t(:btn_create_post), new_user_post_path(current_user), class: 'btn btn-primary col-md-2',
                onclick: 'resetLoginForm()'%>  
                <span>&nbsp&nbsp</span>              
            <% else %>
                <%= link_to t(:btn_create_post), new_user_session_path, class: 'btn btn-primary col-md-2',
                onclick: 'resetLoginForm()' %>
                <span>&nbsp&nbsp</span>
            <% end %>
            <!-- -xử lý đăng nhập/ đăng xuất- -->
            <!-- login button -->
            <!-- show username -->
            <% if user_signed_in? && !current_user.nil? %>
                <div class="dropdown" >
                    <button class="btn btn-info"> <strong><%= current_user.name.first %></strong></button>
                    <div class="dropdown-content">
                        <%= link_to  "#{current_user.name}", edit_user_path(current_user.id), class: 'font-weight-bold' %>
                        <div class="dropdown-divider"></div>
                        <%= link_to  t(:drop_menu_posts), index_user_posts_path(current_user.id) %>
                        <div class="dropdown-divider"></div>
                        <%= link_to  t(:log_out), destroy_user_session_path, method: 'delete' %>
                    </div>
                </div>
            <% else %>
               <!-- <%= link_to 'Đăng nhập', '#loginForm', class: 'btn btn-success',
                onclick: 'resetLoginForm()', data: { toggle: 'modal' } %> -->
                <%= link_to t(:btn_login), new_user_session_path, class: 'btn btn-success col-md-1',
                onclick: 'resetLoginForm()' %>
            <% end %> 
            <!-- .............................................................. -->
            </div> 
            <%# end container bọc nav %>
        </nav>
    </div>

    <div style="padding-top:56px">
    </div>
    <%= yield %>
    <footer class="container-fluid">
        <div class="container">
            <div class="row">
            <div class="col-sm-12">
                <p class="post_span--size-big">About us</p>
            </div>
            </div>
            <div class="row">
            <div class="col-sm-12 col-md-6">
                <p><i class="fa fa-map-marker"></i> 225 Võ Văn Kiệt, Quận 1, Hồ Chí Minh</p>
                <p><i class="fa fa-map-marker"></i> 432/2 Quang Trung, Quận Gò Vấp, Hồ Chí Minh</p>
                <p><i class="fa fa-phone"></i> 0280456214</p>
            </div>
            <div class="col-sm-12 col-md-6">
                <p><a href="#"><i class="fa fa-facebook-official"></i> /everland</a></p>
                <p><a href="#"><i class="fa fa-google-plus-square"></i> /everland</a></p>
            </div>
            </div>
        </div>
    </footer>
    <% if notice || alert %>   
        <div id="snackbar">
            <%= notice %>
            <%= alert %>
        </div>
        <script>
            function myFunction() {
                var x = document.getElementById("snackbar")
                x.className = "show";
                setTimeout(function(){ x.className = x.className.replace("show", ""); }, 5000);
            }
        </script> 
    <% end %>   
</body>
</html>